### PR TITLE
Added support for 5051 wifi/ble sensor

### PR DESCRIPTION
**Pull request by billprozac**
Fixed patch for 5051 sensor

### CODE REVIEW

**Review by Thrilleratplay — APPROVED** [review]
@billprozac  Thanks.  Did you test this to verify it is working correctly?  What is displayed for the battery level?

**Comment by billprozac** [comment]
Bah! I just noticed that in copying the function from the H5074, I left off the battery.  mfg_data[7] is the battery value as it is in for the 5074.  Would you like me to submit a new PR?

**Comment by Thrilleratplay** [comment]
@billprozac   No need for another PR.  If you commit and push the change on the branch, it will update this pull request.  Please let me know if you have tested this and it is working as intended.

**Comment by billprozac** [comment]
Updated and working as expected:
5051_sensor

**Comment by Thrilleratplay** [comment]
Sweet.  Thanks.

**Pull request merged**
