### PR TITLE
Add support for the GoVee H5179 BLE/Wifi combo sensor

### PR DESCRIPTION
**Pull request by skilau**
I bought one of the new (newish?) GoVee H5179 BLE/Wifi combo sensor from Amazon a couple weeks ago.
https://www.amazon.com/gp/product/B0872ZWV8X

It supports retrieving data over Wi-Fi, as well as the standard BLE interface that most of the sensors support.

This patch/pull request just brings in support for the new sensor over BLE.
(Obviously Wi-Fi is not supported)

I tested this at room temperature, and then moved the sensor to my Freezer that sits at about 0 F.
I was able to watch it slowly crawl downwards from about 70 to 0 F. 
Works well, even through the walls of the freezer.

### CODE REVIEW

**Comment by Thrilleratplay** [comment]
@skilau I was going to ask to update the packet with the little endian hex string containing the encode data and tried to piece together what that would be.  By chance did you try the component without any any modifications?  The packet structure looks very similar to the Govee H5051 and may work without any changes.  If not, could you try?

In either case, using `unpack_from` is a much more elegant way to calculate those values.  If the H5051, H5074 and H5179 use the same encoding, I'll adjust your change to check all three devices.

**Comment by skilau** [comment]
Hi @Thrilleratplay !
Thanks for looking at the patch!

I did try the driver without any changes originally, and it did fall into the last "elif" for 5051, like you suggest.
But it was reading at slightly the wrong offset...  (I was getting bad values for everything)

Since I don't have a 5051, I was afraid of trying to combine them, by just changing the offset to read from, since I didn't want to risk breaking the 5051 support.
Like you say, a number of these could be combined into one unpack_from() to read temp, humidity and battery, and just change the offset of which to start from.
(ie, just return an extra offset value when doing the check_is_*() call)

I didn't do it, because I was worried about making the change, and not being able to test all the other models to ensure I didn't break anything, since I don't have them.

PS: The H5179 model has Wi-Fi too, but as far as I can tell, only brings up its TCP/IP stack once every 10 minutes or so, (to save battery power I imagine), to send a data packet to their server.
But it does appear to be able to send slightly more accurate "low" values, as the BLE stops at -4.0F, but the Wi-Fi is able to send down further, (I have seen -4.7F).
Later today, I am going to try to tcpdump/wireshark the data it sends, to see how it sends the data.  On the off chance it sends it unencrypted, or in some way decode-able, I might be able to confirm just how low it can go, and if any other more interesting data is also sent along.

Anyway, thanks again for this driver!
It works extremely well!

**Comment by Thrilleratplay** [comment]
@skilau Thank you for this.  You are correct, the offset is different for the H5051.  I merged in your changes and switched to `unpack_from` to the H5074/H5051.  When you have a chance, can you test v0.9.0 beta 1 to verify everything is working correctly for your H5179?

**Comment by skilau** [comment]
Hi @Thrilleratplay!
Thanks for merging it in.
I can confirm with your latest sources, that all 3 data points (temp, humidity, battery) are all working fine.
(Thanks for making the proper .packet value... I wasn't sure what was supposed to go there)

PS:
For the Wi-Fi part of the H5179 device, I ran tcpdump on my router, just to see what I could see... I was expecting (hoping?) to see that they were sending the data in a safe, encrypted manner....

I was sadly mistaken...
They just do an unencrypted HTTP Post out to their internal server...  Easily decoded by tcpdump.
They send once every 10 minutes, with 10 samples, so presumably, one a minute.
Oh well, thankfully there isn't much/any data in there that needs to be protected...

The tcpdump dump of the packet:

00:53:08.583526 IP (tos 0x0, ttl 128, id 2, offset 0, flags [DF], proto TCP (6), length 429)
    192.168.1.145.20537 > 54.84.35.111.80: Flags [P.], cksum 0x0cc8 (correct), seq 1:390, ack 1, win 5840, length 389: HTTP, length: 389
        POST /th/v2/devices/datas HTTP/1.1
        Host: app.govee.com
        User-Agent: curl/7.58.0
        Accept: */*
        Content-type: application/json
        clientType: 2
        Content-Length: 225

        {"device":"9D:BC:E0:17:54:ZZ:ZZ:ZZ","sku":"H5179","latest":"1","datas":["2170,2390|2170,2390|2170,2390|2170,2380|2170,2380|2180,2380|2180,2390|2180,2380|2190,2370|2190,2370"],"warnType":[0,0],"battery":83,"wifiLevel":-65}

**Comment by Thrilleratplay** [comment]
@skilau Great, I'll release v0.9.0.  I didn't know what the packet value should be either until testing it with my H5074.  I wanted to make sure the values matched past values.  Thank you so much this PR.

The wifi packets traveling over HTTP is not terribly surprising.  It simply reads values, there are no controls, correct?  Seeing that the BLE signal provides more or less provides the same unsecured data....wait.  The host is app.govee.com.  This is not a connection between just the device and cell phone app, it also sends the data to Govee's servers' via clear HTTP?  Yikes.  It is was an ad hoc connection between device and cell phone, that would be one thing.

**Comment by skilau** [comment]
@Thrilleratplay :  Yup!  It goes over the Internet to their server!  No VPN, No TLS/SSL.  UGH!
Pretty bad... Good thing the only thing that might be a little private is the BLE address, and everything is push only, as far as I can tell.
I am leaning towards blocking its access out to the Internet, but that kind of wastes the extra money I paid for this thing. :)

Anyway, thanks again for the driver!

**Pull request merged**
